### ISSUE TITLE
media/embed appeared on the wrong side + random horizontal scroll bars

### ISSUE THREAD

**Issue by 4pii4** [MiyakuKage/discord-momotalk#1]
![image](https://github.com/user-attachments/assets/fda74f4d-881f-4842-b1b1-aaf6c5a0dcc9)
![image](https://github.com/user-attachments/assets/2e8a16c6-f626-44b2-9f3d-188cf6e714b4)

Tested on:
```
stable 315866 (7042d52) Build Override: N/A
Vencord 5160f90 (Vesktop v1.5.2)
Electron 29.1.1
Chromium 122.0.6261.111
```

**Comment by MiyakuKage** [comment]
You have to enable the "Theme Attributes" plugin on Vencord.

**Comment by 4pii4** [comment]
Thanks, this particular issue is fixed
