### ISSUE TITLE
Profile pictures appear over the messages

### ISSUE THREAD

**Issue by ScoutIsDead** [MiyakuKage/discord-momotalk#7]
The profile picture appears on top of the messages while the messages are too far to the left.
And all messages, from you or not, are on the left side, but all messages are on the right. I don't know if that is intended, but the image shown to showcase the theme does not have it that way.

**Comment by NineTwoTen** [comment]
remember to turn on theme attribute in the plugins
![image](https://github.com/user-attachments/assets/ab21e412-3032-486f-9490-d31aa839c75f)

**Comment by ScoutIsDead** [comment]
Oops... I'm dumb. Sorry.
Yeah, that fixed it tho. Thanks.
